
### submit payment
POST http://localhost:8080/v1/submit
Content-Type: application/json

{
  "invoice": 1234568,
  "currency": "EUR",
  "amount": 100,
  "cardholder": {
    "name": "First Last",
    "email": "email@domain.com"
  },
  "card": {
    "pan": "4100000000000001",
    "expiry": "1021",
    "cvv": "789"
  }
}

### get payment by invoice id
GET http://localhost:8080/v1/1234567
